services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file: .env
    volumes:
      - ./:/var/app
    ports:
      - "8080:8080"
    command: /bin/sh -c "go mod download && air -c .air.toml"
